# Generated by Django 3.1.6 on 2021-07-26 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ewasteapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='end_time',
            new_name='ed_time',
        ),
    ]
